# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://myscript.github.io
baseurl: /MyScriptJS
portal: http://www.myscript.com/
devportal: http://dev.myscript.com/
company: MyScript
title: MyScriptJS
subTitle: The JavaScript library for the MyScript Cloud recognition service
description: MyScriptJS is a free and open-source JavaScript library providing the easiest way to use the MyScript Cloud handwriting recognition service in your web app

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
sass:
  style: :compressed

# Compress
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: []
  ignore:
    envs: []

# Gems
gems: []

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

link:
  - title: Getting started
    url: http://doc.myscript.com/MyScriptJS/1.0/html/main/getting-started.html
  - title: Samples
    url: https://github.com/MyScript/MyScriptJS/tree/master/resources/samples
  - title: Documentation
    url: http://doc.myscript.com/MyScriptJS/1.0/index.html
  - title: Reference
    url: http://doc.myscript.com/MyScriptJS/1.0/reference/index.html

social:
  - title: GitHub
    url: https://github.com/MyScript
  - title: Twitter
    url: https://twitter.com/myscript
  - title: Facebook
    url: http://www.facebook.com/MyScriptTechnology
  - title: Google+
    url: https://plus.google.com/+Myscript
  - title: LinkedIn
    url: https://www.linkedin.com/company/myscript
